user:
  # 开关
  start: true
  start-free: false
  start-kingdaili: true
  # 默认返回数据大小
  page-size: 100
  # 库中最小保留可用ip
  min-size: 500
  # ip有效时间，库中ip从入库开始算最长保留时间 /s
  long-time: 1800
  # 获取ip：port的地址访问间隔 /ms
  url-time: 5000
  # 是否开启ip数据验证有效
  check-ip: false
  # 校验地址url= https://www.baidu.com/
  #check-url: "http://www.gsxt.gov.cn/socialuser-use-register.html?aaa="
  check-url: "https://www.baidu.com"
  
  # ip:port 类型的代理地址服务
  urls:
    - "http://api.66daili.cn/API/GetSecretProxy/?orderid=lO8l537l6ZZOlOO3989&num=20&token=66daili&format=text&line_separator=win&protocol=http&region=domestic"
  # 允許更新
  start-upd: false
  # 更新3分钟内的del 2 》》 0
  befor-time: 180
  # 控制删除
  start-del: true
  
  
      
